RELMAN-17 Allow to use credentials to access the catalog file
exoplatform/swf-release-manager pull request #6
Opened 2018-06-19 15:24 UTC by vsellier

- Use jenkins credentials to download the catalog on the pipeline part
- Generate a temporary docker environment file outside the workspace to avoid browsing and pass it to the container.
This will be used is the future to generate dynamically the environment to be able to execute the release elsewhere than prd05

It's also possible to configure the docker command to help during local tests.

2018-06-20 11:23 UTC, fdrouet requested changes

2018-06-20 11:23 UTC, fdrouet commented on orchestrator/do-release/Jenkinsfile
> +        sh "echo -n > ${config.ENV_FILE_FROM_JENKINS}"
be sure that this file is only readable by Jenkins on the system.

2018-06-21 10:56 UTC, vsellier commented on orchestrator/do-release/Jenkinsfile
> +        sh "echo -n > ${config.ENV_FILE_FROM_JENKINS}"
done. the permissions are changed before any writes on the file

2018-06-21 11:54 UTC, fdrouet approved these changes
LGTM

2018-06-22 08:48 UTC, thomasdelhomenie approved these changes

2018-06-25 15:09 UTC, merged